# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: forecast-parser
  pullPolicy: IfNotPresent
  tag: "1.0.0"

#Setup file-mover dependency first
forecastInputVolume: 
  persistentVolumeClaim:
    claimName: forecast-data-pvc

forecastDataVolume:
  accessMode: ReadWriteOnce
  size: 1G
  storageClass: standard

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: forecast-data-pvc

#Specifying local variables
kafka:
  topic: weather-forecast-raw
  host: my-cluster-kafka-brokers
  port: 9092

ksql:
  host: kafka-cp-ksql-server
  port: 8088

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
